Repository playdata-mini-project/horse-racing, pull requests merged in 2023-06, with the labels that each got.

#8 #1 feat: Game Entity 생성
  src/Main.java
  src/domain/entity/Game.java
Labels: 💻 feature

#15 #9 #13 feat: horseReop horseService
  .gitignore
  src/Main.java
  src/config/JdbcConnection.java
  src/controller/Controller.java
  src/controller/HomeController.java
  src/controller/HorseController.java
  src/domain/dto/findAllHorseDto.java
  src/domain/entity/Horse.java
  src/repository/HorseRepository.java
  src/repository/Repository.java
  src/service/HorseService.java
  src/service/Service.java
Labels: 💻 feature

#19 #16 #17 #18 feat: userRepo userService userController
  src/Main.java
  src/controller/HomeController.java
  src/controller/UserController.java
  src/domain/dto/findAllUserDto.java
  src/domain/dto/insertUserDto.java
  src/domain/entity/User.java
  src/repository/UserRepository.java
  src/service/UserService.java
Labels: 💻 feature

#24 #20 #23 feat: GameController Util.Back #22 refactor: dto refactoring
  src/controller/GameController.java
  src/controller/HomeController.java
  src/controller/HorseController.java
  src/controller/UserController.java
  src/domain/dto/FindAllHorseDto.java
  src/domain/dto/FindAllUserDto.java
  src/domain/dto/InsertUserDto.java
  src/repository/HorseRepository.java
  src/repository/UserRepository.java
  src/service/UserService.java
  src/util/Back.java
  src/util/Util.java
Labels: 💻 feature, 🔨 refactor

#30 #14 feat: JdbcConnection
  src/jdbc/JdbcConnection.java
  src/repository/GameRepository.java
  src/sql/QueryExecutor.java
  src/sql/SQLConsumer.java
Labels: 💻 feature

#31 StartGame 생성
  src/controller/GameController.java
  src/repository/GameRepository.java
  src/service/GameService.java
  src/service/Service.java
  src/service/StartGame.java
Labels: 💻 feature

#32 fix: GameRepository
  src/repository/GameRepository.java
Labels: 🔨 refactor

#34 🔨 [REFACTOR] SingleTon 적용, 여러 refactor
  src/Main.java
  src/config/JdbcConnection.java
  src/config/jdbc/JdbcConnection.java
  src/controller/GameController.java
  src/controller/HomeController.java
  src/controller/HorseController.java
  src/controller/UserController.java
  src/domain/dto/BettingDto.java
  src/domain/dto/FindAllHorseDto.java
  src/domain/dto/GameDto.java
  src/domain/dto/InsertUserDto.java
  src/domain/entity/Game.java
  src/domain/entity/Horse.java
  src/domain/entity/User.java
  src/domain/entity/game/Game.java
  src/domain/entity/horse/Horse.java
  src/domain/entity/user/User.java
  src/jdbc/JdbcConnection.java
  src/repository/GameRepository.java
  src/repository/HorseRepository.java
  src/repository/UserRepository.java
  src/service/GameService.java
  src/service/HorseService.java
  src/service/StartGame.java
  src/service/UserService.java
  src/sql/QueryExecutor.java
Labels: 🔨 refactor

#39 solve conflict
  src/sql/QueryExecutor.java
Labels: ✂️ conflict

#41 #40 refactor: HomeController 수정
  src/Main.java
  src/controller/HomeController.java
  src/controller/game/GameController.java
  src/controller/home/HomeController.java
  src/controller/horse/HorseController.java
  src/controller/user/UserController.java
  src/domain/entity/game/Game.java
  src/domain/entity/game/WinningHorses.java
  src/domain/entity/horse/Horse.java
  src/service/Service.java
  src/util/Back.java
  src/util/response/WinnerHorseNamesResponse.java
  src/util/view/HomeViewInput.java
  src/util/view/Output.java
Labels: 🔨 refactor

#43 #42/sudongk refactor: Input, Output 클래스명 수정
  src/config/jdbc/JdbcConnection.java
  src/controller/game/GameController.java
  src/util/view/GameInput.java
  src/util/view/GameOutput.java
Labels: 🔨 refactor

#52 #49 #50 #51 refactor: Match Class 추가, 중복 코드 제거, 코드 간결화, WinningHorse,…
  src/controller/game/GameController.java
  src/domain/entity/game/Game.java
  src/domain/entity/game/Match.java
  src/domain/entity/game/Winners.java
  src/domain/entity/game/WinningHorses.java
  src/domain/entity/horse/Horses.java
  src/domain/entity/user/Users.java
  src/util/response/FinalPositionResp.java
  src/util/response/WinnerHorseNamesResp.java
  src/util/response/WinningUserNamesResp.java
  src/util/view/GameOutput.java
  src/util/view/HomeViewInput.java
Labels: 🔨 refactor
